### ISSUE TITLE
Expand regex lecture

### ISSUE THREAD

**Issue by rolandkrause** [LSRU/tv_course#1]
- Negative and positive look ahead
- Better structure
- Application within dplyr
- Integration with stringr package where useful

See presentation in ISB101 class (Janos Binder et al.)

**Comment by ginolhac** [comment]
with real-case such as:

- str_split with purrr::reduce (size -> volume)
- str_extract -> parse_number
- str_match for fetching ids with grouped patterns

**Comment by ginolhac** [comment]
project lives here now https://git-r3lab.uni.lu/aurelien.ginolhac/rworkshop/issues
