### ISSUE TITLE
explain paths in readr lecture

### ISSUE THREAD

**Issue by koncina** [LSRU/tv_course#4]
Do not use the `readxl::readxl_example()` and `readr::readr_example()` anymore. Put the files online et let the people download the files to their project folder.

**Explain**
- relative vs absolute path
- project vs setwd()
- knit -> knit directory (newer Rstudio feature?)

**Comment by ginolhac** [comment]
please see the great [twee()](https://gist.github.com/jennybc/2bf1dbe6eb1f261dfe60) by the incredible Jenny

**Comment by ginolhac** [comment]
project lives here now https://git-r3lab.uni.lu/aurelien.ginolhac/rworkshop/issues
