### ISSUE TITLE
broken link Lecture 2, line 222

### ISSUE THREAD

**Issue by orchid00** [LSRU/tv_course#9]
Lecture 2, line 222 has a broken link
https://ironholds.org/projects/rbitrary/#okay.-and-should-we-be-using---or-people-keep-telling-me-to-use--

I will suggest to add 
http://adv-r.had.co.nz/Style.html

**Comment by ginolhac** [comment]
project lives here now https://git-r3lab.uni.lu/aurelien.ginolhac/rworkshop/issues
